"""Початкова схема касової книги

Revision ID: 2df48b7b870e
Revises: 
Create Date: 2026-09-17 14:33:15.921094

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('edrpou', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('subdivision', sa.String(length=255), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.Column('chief_accountant', sa.String(length=150), nullable=True),
    sa.Column('cashier', sa.String(length=150), nullable=True),
    sa.Column('cash_limit', sa.BigInteger(), nullable=False),
    sa.Column('limit_order', sa.String(length=255), nullable=True),
    sa.Column('book_started_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counterparty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=True),
    sa.Column('id_document', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.create_index('ix_counterparty_name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('cash_book_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('opening_balance', sa.BigInteger(), nullable=False),
    sa.Column('total_in', sa.BigInteger(), nullable=False),
    sa.Column('total_out', sa.BigInteger(), nullable=False),
    sa.Column('closing_balance', sa.BigInteger(), nullable=False),
    sa.Column('salary_balance', sa.BigInteger(), nullable=False),
    sa.Column('docs_in_count', sa.Integer(), nullable=False),
    sa.Column('docs_out_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('cashier_name', sa.String(length=150), nullable=True),
    sa.Column('accountant_name', sa.String(length=150), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('printed_count', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_date'),
    sa.UniqueConstraint('year', 'number', name='uq_sheet_year_number')
    )
    with op.batch_alter_table('cash_book_sheet', schema=None) as batch_op:
        batch_op.create_index('ix_sheet_date', ['sheet_date'], unique=False)

    op.create_table('cash_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_text', sa.String(length=255), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('appendix', sa.Text(), nullable=True),
    sa.Column('id_document', sa.String(length=255), nullable=True),
    sa.Column('corr_account_id', sa.Integer(), nullable=True),
    sa.Column('corr_account_code', sa.String(length=10), nullable=True),
    sa.Column('analytic_code', sa.String(length=20), nullable=True),
    sa.Column('purpose_code', sa.String(length=10), nullable=True),
    sa.Column('is_salary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_order_amount_positive'),
    sa.ForeignKeyConstraint(['corr_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['cash_book_sheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'year', 'number', name='uq_order_kind_year_number')
    )
    with op.batch_alter_table('cash_order', schema=None) as batch_op:
        batch_op.create_index('ix_order_date', ['doc_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_order', schema=None) as batch_op:
        batch_op.drop_index('ix_order_date')

    op.drop_table('cash_order')
    with op.batch_alter_table('cash_book_sheet', schema=None) as batch_op:
        batch_op.drop_index('ix_sheet_date')

    op.drop_table('cash_book_sheet')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))

    op.drop_table('audit_log')
    op.drop_table('users')
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.drop_index('ix_counterparty_name')

    op.drop_table('counterparty')
    op.drop_table('company')
    op.drop_table('account')
    # ### end Alembic commands ###
