"""Підписанти без головного бухгалтера, ролі директора і старшого касира

Revision ID: 582db765e092
Revises: 0001_initial
Create Date: 2026-09-17 14:52:19.369146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_signatories'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_chief_accountant', sa.Boolean(),
                                      nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('accountant_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accountant_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('authorization_order', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cashier_order', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('cashier_order')
        batch_op.drop_column('authorization_order')
        batch_op.drop_column('accountant_name')
        batch_op.drop_column('accountant_title')
        batch_op.drop_column('has_chief_accountant')
        batch_op.drop_column('director_title')

    # ### end Alembic commands ###
