"""Каси ПРРО та реквізити Z-звіту в ордері

Revision ID: 844d9b07f0f3
Revises: 0002_signatories
Create Date: 2026-09-17 16:24:44.490349

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0003_prro'
down_revision = '0002_signatories'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos_terminal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fiscal_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_number')
    )
    with op.batch_alter_table('cash_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=10),
                                      nullable=False, server_default='general'))
        batch_op.add_column(sa.Column('pos_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('z_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('z_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('card_amount', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint('uq_order_pos_z', ['pos_id', 'z_number'])
        batch_op.create_foreign_key('fk_order_pos', 'pos_terminal',
                                    ['pos_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_pos', type_='foreignkey')
        batch_op.drop_constraint('uq_order_pos_z', type_='unique')
        batch_op.drop_column('card_amount')
        batch_op.drop_column('z_date')
        batch_op.drop_column('z_number')
        batch_op.drop_column('pos_id')
        batch_op.drop_column('source')

    op.drop_table('pos_terminal')
    # ### end Alembic commands ###
